In [1]:
print("hola")

hola

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

In [5]:
data = {
    "comentario": [
        "Buen servicio",
        "Mala atención",
        "Regular",
        "Excelente trabajo",
        "Pésima gestión"
    ],
    "sentimiento": [
        "positivo",
        "negativo",
        "neutral",
        "positivo",
        "negativo"
    ]
}

df = pd.DataFrame(data)
df

          comentario sentimiento
0      Buen servicio    positivo
1      Mala atención    negativo
2            Regular     neutral
3  Excelente trabajo    positivo
4     Pésima gestión    negativo

In [6]:
X = df["comentario"]
y = df["sentimiento"]

In [7]:
vectorizer = CountVectorizer()
X_vec = vectorizer.fit_transform(X)

In [8]:
modelo = MultinomialNB()
modelo.fit(X_vec, y)

MultinomialNB()

In [10]:
texto_prueba = ["La municipalidad trabaja bien"]
texto_vec = vectorizer.transform(texto_prueba)

prediccion = modelo.predict(texto_vec)
print(prediccion)

['negativo']

In [12]:
modelo.predict(vectorizer.transform(["Buen servicio"]))

array(['positivo'], dtype='<U8')

In [13]:
import pickle

pickle.dump((modelo, vectorizer), open("modelo.pkl", "wb"))

In [14]:
data = {
    "comentario": [
        "Buen servicio",
        "Excelente trabajo",
        "Muy buena atención",
        "Mala atención",
        "Pésima gestión",
        "Muy mal servicio",

        "Servicio regular",
        "Atención normal",
        "No está mal ni bien",
        "Servicio aceptable",
        "Todo normal",
        "Sin inconvenientes"
    ],
    "sentimiento": [
        "positivo",
        "positivo",
        "positivo",
        "negativo",
        "negativo",
        "negativo",

        "neutral",
        "neutral",
        "neutral",
        "neutral",
        "neutral",
        "neutral"
    ]
}

In [15]:
texto_prueba = ["No esta ni bien , ni mal "]
texto_vec = vectorizer.transform(texto_prueba)

prediccion = modelo.predict(texto_vec)
print(prediccion)

['negativo']

In [16]:
import pickle
pickle.dump((modelo, vectorizer), open("modelo.pkl", "wb"))

In [34]:
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

data = {
    "comentario": [
        # positivos
        "Buen servicio",
"Muy buen servicio",
"Excelente servicio",
"Servicio eficiente",
"Servicio de calidad",
"Buena atención",
"Muy buena atención",
"Excelente atención",
        "Al fin se está logrando con la construcción del puente de pisquillo. Siempre habrá críticas porque no a todos les parece bien. Felicitaciones sr alcalde y alos Pobladores de pisquillo por este logro hecho realidad.",
        "Por ahora magnifico",
        "ME PARECE QUE LOS HECHOS DARAN CREDIBILIDAD A LA GESTIÓN, POR AHORA MAGNÍFICO, SALUDOS VICTOR UN GRAN ABRAZOTE... SALUDOS FRATERNOS A TODA MI LINDA GENTE DE PISQUILLO DIOS PADRE TODOPODEROSO ETERNO Y VERDADERO OS BENDIGA AMÉN.UN GRAN ABRAZOTE A CADA UNO HERMANOS",

        # negativos
        "Mala gestión municipal",
        "No hacen nada por el pueblo",
        "Pésima atención",
        "Todo es mentira",
        "No cumplen lo que prometen",
        "La municipalidad no responde",
        "Hay mucha demora",
        "Mal trabajo del alcalde",
        "No solucionan los problemas",
        "Solo quieren llevarse el crédito",

        # neutrales
        "Servicio regular",
        "Atención normal",
        "Todo sigue igual",
        "Sin novedades",
        "Información publicada",
        "Se realizó una actividad",
        "La obra continúa en proceso",
        "Comentario informativo",
        "El comunicado fue publicado",
        "No esta ni bien ni mal"
    ],
    "sentimiento": [
        # positivos
        "positivo", "positivo", "positivo", "positivo", "positivo",
        "positivo", "positivo", "positivo", "positivo", "positivo",
        "positivo",
        

        # negativos
        "negativo", "negativo", "negativo", "negativo", "negativo",
        "negativo", "negativo", "negativo", "negativo", "negativo",

        # neutrales
        "neutral", "neutral", "neutral", "neutral", "neutral",
        "neutral", "neutral", "neutral", "neutral", "neutral"
    ]
}

df = pd.DataFrame(data)

X = df["comentario"]
y = df["sentimiento"]

vectorizer = TfidfVectorizer(ngram_range=(1, 2), lowercase=True)
X_vec = vectorizer.fit_transform(X)

modelo = MultinomialNB()
modelo.fit(X_vec, y)

pruebas = [
    "No está mal ni bien",
    "El servicio fue regular",
    "La atención fue normal",
    "Buen servicio",
    "Pésima gestión",
    "ME PARECE QUE LOS HECHOS DARAN CREDIBILIDAD A LA GESTIÓN, POR AHORA MAGNÍFICO, SALUDOS VICTOR UN GRAN ABRAZOTE... SALUDOS FRATERNOS A TODA MI LINDA GENTE DE PISQUILLO DIOS PADRE TODOPODEROSO ETERNO Y VERDADERO OS BENDIGA AMÉN.UN GRAN ABRAZOTE A CADA UNO HERMANOS"
    "Al fin se está logrando con la construcción del puente de pisquillo. Siempre habrá críticas porque no a todos les parece bien. Felicitaciones sr alcalde y alos Pobladores de pisquillo por este logro hecho realidad.",
        "Por ahora magnifico",
]

for texto in pruebas:
    pred = modelo.predict(vectorizer.transform([texto]))[0]
    print(texto, "=>", pred)

pickle.dump((modelo, vectorizer), open("modelo.pkl", "wb"))

No está mal ni bien => neutral
El servicio fue regular => neutral
La atención fue normal => neutral
Buen servicio => positivo
Pésima gestión => negativo
ME PARECE QUE LOS HECHOS DARAN CREDIBILIDAD A LA GESTIÓN, POR AHORA MAGNÍFICO, SALUDOS VICTOR UN GRAN ABRAZOTE... SALUDOS FRATERNOS A TODA MI LINDA GENTE DE PISQUILLO DIOS PADRE TODOPODEROSO ETERNO Y VERDADERO OS BENDIGA AMÉN.UN GRAN ABRAZOTE A CADA UNO HERMANOSAl fin se está logrando con la construcción del puente de pisquillo. Siempre habrá críticas porque no a todos les parece bien. Felicitaciones sr alcalde y alos Pobladores de pisquillo por este logro hecho realidad. => positivo
Por ahora magnifico => positivo

In [7]:
# =====================================
# DATASET FILTRO
# =====================================

data_filtro = {

    "texto": [

        # VALIDOS

        "Pésima gestión",
        "Excelente iniciativa",
        "Muy buena atención",
        "La municipalidad debería mejorar",
        "Buen trabajo alcalde",
        "No cumplen lo prometido",
        "La atención es lenta",

        # RUIDO

        "Número de notificaciones no leídas",
        "Crear cuenta",
        "Messenger",
        "Compartir",
        "Correo electrónico",
        "Meta",
        "Escribe un comentario",
    ],

    "tipo": [

        # VALIDOS

        "valido",
        "valido",
        "valido",
        "valido",
        "valido",
        "valido",
        "valido",

        # RUIDO

        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
    ]
}

In [8]:
df_filtro = pd.DataFrame(data_filtro)

df_filtro.head()

NameError: name 'pd' is not defined

In [3]:
X_filtro = df_filtro["texto"]

y_filtro = df_filtro["tipo"]

NameError: name 'df_filtro' is not defined

In [4]:
vectorizer_filtro = TfidfVectorizer()

X_filtro_vec = vectorizer_filtro.fit_transform(
    X_filtro
)

NameError: name 'TfidfVectorizer' is not defined

In [ ]:
modelo_filtro = MultinomialNB()

modelo_filtro.fit(
    X_filtro_vec,
    y_filtro
)

In [6]:
pruebas_filtro = [

    "Número de notificaciones no leídas",

    "Excelente trabajo municipal",

    "Messenger",

    "Pésima gestión",

    "Compartir",

    "La atención fue lenta"
]

for texto in pruebas_filtro:

    pred = modelo_filtro.predict(

        vectorizer_filtro.transform(
            [texto]
        )

    )[0]

    print(texto, "=>", pred)

NameError: name 'modelo_filtro' is not defined

In [1]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

import pickle

In [2]:
data_filtro = {

    "texto": [

        "Pésima gestión",
        "Excelente iniciativa",
        "Muy buena atención",
        "La municipalidad debería mejorar",

        "Número de notificaciones no leídas",
        "Crear cuenta",
        "Messenger",
        "Compartir",
        "Meta",
    ],

    "tipo": [

        "valido",
        "valido",
        "valido",
        "valido",

        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
    ]
}

In [3]:
df_filtro = pd.DataFrame(data_filtro)

df_filtro.head()

                                texto    tipo
0                      Pésima gestión  valido
1                Excelente iniciativa  valido
2                  Muy buena atención  valido
3    La municipalidad debería mejorar  valido
4  Número de notificaciones no leídas   ruido

In [4]:
X_filtro = df_filtro["texto"]

y_filtro = df_filtro["tipo"]

In [5]:
vectorizer_filtro = TfidfVectorizer()

X_filtro_vec = vectorizer_filtro.fit_transform(
    X_filtro
)

In [6]:
modelo_filtro = MultinomialNB()

modelo_filtro.fit(
    X_filtro_vec,
    y_filtro
)

MultinomialNB()

In [7]:
pruebas_filtro = [

    "Número de notificaciones no leídas",

    "Excelente trabajo municipal",

    "Messenger",

    "Pésima gestión"
]

for texto in pruebas_filtro:

    pred = modelo_filtro.predict(

        vectorizer_filtro.transform(
            [texto]
        )

    )[0]

    print(texto, "=>", pred)

Número de notificaciones no leídas => ruido
Excelente trabajo municipal => valido
Messenger => ruido
Pésima gestión => valido

In [8]:
pickle.dump(

    (modelo_filtro, vectorizer_filtro),

    open(
        "modelo_filtro.pkl",
        "wb"
    )
)

In [19]:
data_filtro = {

    "texto": [

        "Pésima gestión",
        "Excelente iniciativa",
        "Muy buena atención",
        "La municipalidad debería mejorar",

        "Número de notificaciones no leídas",
        "Crear cuenta",
        "Messenger",
        "Compartir",
        "Meta",
        "Se seleccionó la opción Más relevantes, por lo que es posible que algunos comentarios se hayan filtrado",
    ],

    "tipo": [

        "valido",
        "valido",
        "valido",
        "valido",

        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
        "ruido",
    ]
}

In [22]:
df_filtro = pd.DataFrame(data_filtro)

df_filtro.head()

                                texto    tipo
0                      Pésima gestión  valido
1                Excelente iniciativa  valido
2                  Muy buena atención  valido
3    La municipalidad debería mejorar  valido
4  Número de notificaciones no leídas   ruido

In [23]:
X_filtro = df_filtro["texto"]

y_filtro = df_filtro["tipo"]

In [24]:
vectorizer_filtro = TfidfVectorizer()

X_filtro_vec = vectorizer_filtro.fit_transform(
    X_filtro
)

In [25]:
modelo_filtro = MultinomialNB()

modelo_filtro.fit(
    X_filtro_vec,
    y_filtro
)

MultinomialNB()

In [26]:
pruebas_filtro = [

    "Número de notificaciones no leídas",

    "Excelente trabajo municipal",

    "Messenger",

    "Pésima gestión",

    "Compartir",

    "La atención fue lenta",
   "Se seleccionó la opción Más relevantes, por lo que es posible que algunos comentarios se hayan filtrado"
]

for texto in pruebas_filtro:

    pred = modelo_filtro.predict(

        vectorizer_filtro.transform(
            [texto]
        )

    )[0]

    print(texto, "=>", pred)

Número de notificaciones no leídas => ruido
Excelente trabajo municipal => valido
Messenger => ruido
Pésima gestión => valido
Compartir => ruido
La atención fue lenta => valido
Se seleccionó la opción Más relevantes, por lo que es posible que algunos comentarios se hayan filtrado => ruido

In [15]:
pickle.dump(

    (modelo_filtro, vectorizer_filtro),

    open(
        "modelo_filtro.pkl",
        "wb"
    )
)